services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=eureka-server
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - duoc-music-hub-net

networks:
  duoc-music-hub-net:
    driver: bridge