spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${server.port}/eureka/
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: true
server:
  port: 8761
